"""Application identity and GSettings access.

Every identifier the desktop cares about — the D-Bus name, the ``.desktop``
file, the icon, the AppStream component, the WM class — has to be one and the
same string, so it is defined once here.
"""

import functools
import logging
from pathlib import Path

from gtkpass._gi import Gio

log = logging.getLogger(__name__)

#: Reverse-DNS application identifier, following the GNOME/Flathub convention.
APP_ID = "io.github.RonnyPfannschmidt.GTKPass"

#: Identifier of the top level GSettings schema.
SCHEMA_ID = APP_ID

#: Object path of the top level schema, derived from APP_ID as GLib expects.
SCHEMA_PATH = "/" + APP_ID.replace(".", "/") + "/"

#: Relocatable schema identifier for per-backend configuration.
BACKEND_SCHEMA_ID = SCHEMA_ID + ".backend.{backend_type}"

#: Object path for a backend instance's relocatable schema.
BACKEND_SCHEMA_PATH = SCHEMA_PATH + "backends/{backend_id}/"


#: Where a systemd-sysext build compiles this application's schema.
#:
#: It cannot install into ``/usr/share/glib-2.0/schemas``: the
#: ``gschemas.compiled`` there is a single file holding every application's
#: schemas, and a sysext is an overlay rather than a merge, so an image shipping
#: its own copy would hide all of them and the session would come up without
#: GNOME's own settings.  See docs/PACKAGING.md.
#:
#: The plain RPM does install into the system directory and ships nothing here,
#: which is why this is added to the search path rather than used in place of it.
BUNDLED_SCHEMA_DIR = Path("/usr/share/gtkpass/schemas")


class SchemaNotInstalledError(RuntimeError):
    """Raised when the GSettings schema cannot be found."""


@functools.cache
def schema_source() -> Gio.SettingsSchemaSource | None:
    """The schema source to look schemas up in, cached for the process.

    GLib caches its own default source on first use, and this wraps that with
    :data:`BUNDLED_SCHEMA_DIR` when a build has put a schema there.
    """
    default = Gio.SettingsSchemaSource.get_default()
    if not (BUNDLED_SCHEMA_DIR / "gschemas.compiled").exists():
        return default
    try:
        return Gio.SettingsSchemaSource.new_from_directory(
            str(BUNDLED_SCHEMA_DIR), default, True
        )
    except Exception:
        # A truncated or foreign gschemas.compiled must not take the
        # application down at startup. Falling back leaves it reporting a
        # missing schema, which someone can act on.
        log.warning("ignoring unreadable schema directory %s", BUNDLED_SCHEMA_DIR)
        return default


def _lookup(schema_id: str) -> Gio.SettingsSchema:
    """Resolve a schema, or raise something a human can act on.

    ``Gio.Settings.new()`` on an unknown schema calls ``g_error()``, which
    aborts the process outright — it is not a Python exception and leaves no
    traceback.  Always look the schema up first.
    """
    source = schema_source()
    schema = source.lookup(schema_id, True) if source is not None else None
    if schema is None:
        raise SchemaNotInstalledError(
            f"GSettings schema {schema_id!r} is not installed.\n"
            f"Run 'glib-compile-schemas data/' and set "
            f"GSETTINGS_SCHEMA_DIR to that directory, or install the schema "
            f"into a system schema directory."
        )
    return schema


def get_settings() -> Gio.Settings:
    """Settings for the application itself."""
    return Gio.Settings.new_full(_lookup(SCHEMA_ID), None, None)


def get_backend_settings(backend_type: str, backend_id: str) -> Gio.Settings:
    """Settings for one configured backend instance.

    Args:
        backend_type: Which backend implementation (``demo``, ``pass``, ...).
        backend_id: Unique identifier of this configured instance.
    """
    schema_id = BACKEND_SCHEMA_ID.format(backend_type=backend_type)
    path = BACKEND_SCHEMA_PATH.format(backend_id=backend_id)
    return Gio.Settings.new_full(_lookup(schema_id), None, path)


#: Readable labels for the backends shipped with the application.
BACKEND_TYPE_NAMES = {
    "demo": "Demo",
    "secretservice": "Secret Service",
    "pass": "Pass",
    "direct": "Direct GPG",
}


def derive_backend_display_name(backend_type: str, backend_id: str) -> str:
    """The name to show for an instance the user has not named.

    Instance ids generated by the settings dialog look like ``demo_1766234611``
    and carry no information worth showing, so those fall back to the backend
    type. An id the user chose is shown as written.
    """
    parts = backend_id.split("_")
    if len(parts) >= 2 and parts[-1].isdigit():
        return BACKEND_TYPE_NAMES.get(backend_type, backend_type.title())
    return backend_id.replace("_", " ").title()


def get_backend_display_name(backend_type: str, backend_id: str) -> str:
    """Name to show for a backend instance, as configured or derived."""
    stored = get_backend_settings(backend_type, backend_id).get_string("display-name")
    return stored.strip() or derive_backend_display_name(backend_type, backend_id)


def set_backend_display_name(backend_type: str, backend_id: str, name: str) -> None:
    """Store a user-chosen name; an empty one restores the derived default."""
    settings = get_backend_settings(backend_type, backend_id)
    settings.set_string("display-name", name.strip())
